### PR TITLE
Adds support to create HighSierra Beta bootable ISO.

### PR DESCRIPTION
**Pull request by farkasseb**
This PR aims to support **HighSierra Beta** bootable ISO creation. To achieve this goal I am using `createinstallmedia` which is bundled into the Installer.app.

The ISO creation works, but I couldn't complete the installation successfully on VirtualBox (version 5.1.22 r115126 (Qt5.6.2)). The installers boots successfully and formatting the disk to APFS also works. After these steps the installation process seems to finish as well. However, during the first boot (from disk) I get a boot failure (*Boot Failed Mac OS X*) and the UEFI interactive shell is presented instead of the working system. (I am pretty sure that this is not related to the ISO creation.)

Please note that I couldn't test my changes with previous installers, only the beta one.
Any constructive comment is highly appreciated. 🙂

### CODE REVIEW

**Comment by geerlingguy** [comment]
This is changing a _lot_ of the script; one goal I have is to make it so people can still work with older OSes (at least n-2 releases), and it seems like some of that legacy support is being removed in here.

I know it's a work in progress, but just want to make it clear that anything for High Sierra would need to be in addition to the already-supported OSes.

**Comment by farkasseb** [comment]
I know it is changing a lot and it might break older versions. My main goal with this PR was that if someone tests it and has any idea why High Sierra installation won't complete will share that information.

**Comment by ItzLevvie** [comment]
@farkasseb 

Have you made sure that "Mac OS X (64-bit)" is checked in General --> Basic --> Version?

**Comment by lony** [comment]
Made a PR https://github.com/geerlingguy/macos-virtualbox-vm/pull/37 using @grahamperrin gist from here https://github.com/geerlingguy/macos-virtualbox-vm/issues/28

**Comment by geerlingguy** [comment]
See #39.

**Pull request closed without merging**
