### PR TITLE
Added changes to fix issue #73 and added support for Catalina

### PR DESCRIPTION
**Pull request by cipaterson**
My first pull request... Go easy on me if I've not followed conventions correctly.
I fixed path changes reported in issue #73 for Mojave and added support for Catalina.
Making a Catalina iso works fine for me, but I had to work around the "operation not permitted" error from asr.

### CODE REVIEW

**Review by geerlingguy — APPROVED** [review]

**Comment by geerlingguy** [comment]
Remind me if I don't get around to merging this soon :D

**Comment by geerlingguy** [comment]
lol oops!

**Comment by geerlingguy** [comment]
Hmm... this is conflicting with the addition of Big Sur. Can you rebase with the latest changes?

**Comment by catap** [comment]
@geerlingguy let ask @cipaterson ! I just read this issues and when I read that you asked to ping you if you forgot about that... well.. I've pinged you :)

**Comment by cipaterson** [comment]
@geerlingguy, @catap , I have rebased the Big Sur changes into my fork/branch.  My existing pull request should merge clean now.
I don't think the script will produce a Big Sur iso as the other if statements need to be altered too (as Jeff noted).  Maybe the way to fix that is to "invert" the if/else causes.  i.e. put the latest working case in the else and the code for earlier MacOS installers in explicit if clauses.  Like this:
    echo Remove Package link and replace with actual files
    echo --------------------------------------------------------------------------
    if [ "${isoName}" == "Yosemite" ] || [ "${isoName}" == "ElCapitan" || [ "${isoName}" == "Sierra" ] ; then
      echo $ rm /Volumes/OS\ X\ Base\ System/System/Installation/Packages
      rm /Volumes/OS\ X\ Base\ System/System/Installation/Packages
      echo $ cp -rp /Volumes/install_app/Packages /Volumes/OS\ X\ Base\ System/System/Installation/
      cp -rp /Volumes/install_app/Packages /Volumes/OS\ X\ Base\ System/System/Installation/
    elif [ "${isoName}" == "HighSierra" ] ; then
      echo $ ditto -V /Volumes/install_app/Packages /Volumes/OS\ X\ Base\ System/System/Installation/
      ditto -V /Volumes/install_app/Packages /Volumes/OS\ X\ Base\ System/System/Installation/
    else
      echo $ ditto -V /Volumes/install_app/Packages /Volumes/macOS\ Base\ System/System/Installation/
      ditto -V /Volumes/install_app/Packages /Volumes/macOS\ Base\ System/System/Installation/
    fi
Then any latest installer added has some hope it will just work (if it works like the last version)...

**Comment by catap** [comment]
@cipaterson I agree with you that this script won't work with Big Sur. Why? Because Big Sur installer contains `SharedSupport.dmg` instead of `InstallESD.dmg` and structure is quite different.

**Pull request merged**
