### PR TITLE
Fix Monterey support

### PR DESCRIPTION
**Pull request by zmizik**
Added support for Monterey. Tested with 12.2.1.  Source merged with BigSur support.

### CODE REVIEW

**Comment by jbeard6** [comment]
I used this to create an installer ISO for macOS Monterey. I used the installer in Virtualbox, which seems to install successfully, but is failing to actually start the VM. I'm still researching that, but I don't think it's related to these changes, FWIW.

**Comment by jbeard6** [comment]
It turns out, I missed a step in the README when setting up my test VM (`VBoxManage modifyvm VM_NAME --cpuidset 00000001 000306a9 00020800 80000201 178bfbff`). Starting over following the steps exactly worked.

I'd be happy to take a swag at re-building this pull request without the spurious formatting changes if you'd be more amenable to merging it that way.

**Comment by zmizik** [comment]
Frankly, I didn't pay attention to formatting. I took a fork from ansonhoyte and simply added new filters. Feel free to reformat the code.

**Comment by geerlingguy** [comment]
See #89

**Pull request closed without merging**
